streamlit 1.37.0
AnacondaRecipes/streamlit-feedstock pull request #11
Opened 2024-08-14 22:11 UTC by psteyer

streamlit 1.37.0 

**Destination channel:** Defaults

### Links

- [PKG-5416]
- dev_url:        https://github.com/streamlit/streamlit/tree/release/1.37.0
- conda_forge:    None
- pypi:           https://pypi.org/project/streamlit/1.37.0
- pypi inspector: https://inspector.pypi.io/project/streamlit/1.37.0/

### Explanation of changes:

- ...

2024-08-15 15:50 UTC, ifitchet commented
There's a Python restriction, `!=3.9.7`: https://inspector.pypi.io/project/streamlit/1.37.0/packages/68/b1/3fd1ae1e313f819a9e57272bd820130dd38e43bcbe9846ceba89345d45a6/streamlit-1.37.0.tar.gz/streamlit-1.37.0/setup.py#line.143

2024-08-16 19:57 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_568nn06cpi/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:24: remove_python_pinning: On arch specific packages, python deps should not be constrained.
- clone/recipe/meta.yaml:45: remove_python_pinning: On arch specific packages, python deps should not be constrained.
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-08-19 17:29 UTC, ifitchet requested changes

2024-08-19 17:29 UTC, ifitchet commented on recipe/meta.yaml
> +  skip: true  # [s390x or py<=38]
Based on `Requires-Python: >=3.8, !=3.9.7`?:

```suggestion
  skip: true  # [s390x or py<38]
```

2024-08-20 14:23 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_102euk6yr6/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:45: remove_python_pinning: On arch specific packages, python deps should not be constrained.
- clone/recipe/meta.yaml:24: remove_python_pinning: On arch specific packages, python deps should not be constrained.
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-08-20 22:26 UTC, Jrice1317 commented on recipe/meta.yaml
>      - tornado >=6.0.3,<7
```suggestion
    - tornado >=6.0.3,<7
    run_constrained:
    - snowflake-snowpark-python >=0.9.0 # [py<312]
    - snowflake-connector-python >=2.8.0 # [py<312]
```

2024-08-20 22:28 UTC, Jrice1317 commented on recipe/meta.yaml
>      - tornado >=6.0.3,<7
Maybe we should add [these](https://github.com/streamlit/streamlit/blob/1.37.1/lib/setup.py#L72-L77) to run_constrained?

2024-08-20 22:31 UTC, Jrice1317 reviewed
Outside of adding the extra requires with pinnings to run constrained, LGTM

2024-08-20 22:32 UTC, Jrice1317 approved these changes

2024-08-21 15:07 UTC, psteyer commented on recipe/meta.yaml
>      - tornado >=6.0.3,<7
added, and moved python skip to `run_constrained` also. Thank you!

2024-08-21 21:13 UTC, JeanChristopheMorinPerso approved these changes

2024-08-22 08:52 UTC, ifitchet approved these changes
Huh, the old `run_constrained` trick.

2024-08-22 13:58 UTC, merged