streamlit 1.26.1
AnacondaRecipes/streamlit-feedstock pull request #12
Opened 2024-10-02 19:52 UTC by msentissi

{streamlit} {1.26.1}

**Destination channel:** defaults

### Links

- [PKG-5771](https://anaconda.atlassian.net/browse/PKG-5771) 
- [Upstream repository](https://github.com/streamlit/streamlit/tree/1.26.1)

### Explanation of changes:

- Removed License file under recipe/
- Included snowflake-snowpark-python, which was an extra, as a run requirement as I couldn't find a fixed policy regarding extras. My understanding is that it's a case-by-case matter, whether we decide to create a multi-output recipe, or exclude the extra, or include it.

2024-10-02 19:53 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_db8lut1fmm/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:51: remove_python_pinning: On arch specific packages, python deps should not be constrained.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-10-02 23:13 UTC, ryanskeith reviewed
Please see comments.  I think we should make a few changes before it is merged.

2024-10-02 23:13 UTC, ryanskeith commented on recipe/meta.yaml
> +    - snowflake-snowpark-python
```suggestion
```
I always recommend not including extras.  We don't want to be opinionated on the user's behalf in most cases.  Also note that in this case this particular dependency is only for Python 3.8 https://github.com/streamlit/streamlit/blob/468ea55dc453bce87e4ba4034fa304af11af3350/lib/setup.py#L83.  So I would leave it off completely as there is no constraint to constrain on.

2024-10-02 23:13 UTC, ryanskeith commented on recipe/meta.yaml
> +  skip: true                            # [s390x or py<38 or py>311]
I am not seeing where the code constrains this to Python lower than Python 3.11.  Would you show me the source of this decision?

2024-10-02 23:15 UTC, ryanskeith requested changes
Please reach out to me if you have questions.

2024-10-02 23:24 UTC, ryanskeith commented on recipe/meta.yaml
> +  license_url: https://github.com/streamlit/streamlit/blob/1.26.1/LICENSE
I am flexible if we want to just point to the license online BUT if we do, I wouldn't point to the specific github tagged version, I would point to the main branch as this would make updating the file more work.

2024-10-02 23:25 UTC, ryanskeith commented on recipe/meta.yaml
> +  license_url: https://github.com/streamlit/streamlit/blob/1.26.1/LICENSE
Otherwise just revert the license file as they aren't packaging the license file in the PyPI package.

2024-10-03 07:29 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - snowflake-snowpark-python
We should follow the same logic as we did for `streamlit 1.37.1` https://github.com/AnacondaRecipes/streamlit-feedstock/blob/main/recipe/meta.yaml#L43-L49

2024-10-03 14:06 UTC, msentissi commented on recipe/meta.yaml
> +  license_url: https://github.com/streamlit/streamlit/blob/1.26.1/LICENSE
> Let's just keep the license file as is. It will use the LICENSE file in the github download

The source is pypi, and the license is not included in it.

2024-10-03 14:19 UTC, msentissi commented on recipe/meta.yaml
> +  license_url: https://github.com/streamlit/streamlit/blob/1.26.1/LICENSE
I reverted the license file and removed license_url.

2024-10-03 14:34 UTC, msentissi commented on recipe/meta.yaml
> +  skip: true                            # [s390x or py<38 or py>311]
I removed it only because it wasn't listed in the classifiers list, but I'm not sure that's something we are meant to base these decisions on ?

2024-10-03 14:41 UTC, msentissi commented on recipe/meta.yaml
> +    - snowflake-snowpark-python
As I stated in the PR description, I was uncertain about the way to deal with extras. I've removed it from the recipe for now as suggested by @ryanskeith. 
@skupr-anaconda I did take a look at that version but I didn't quite understand the logic in [`streamlit 1.37.1`](https://github.com/AnacondaRecipes/streamlit-feedstock/blob/main/recipe/meta.yaml#L43-L49). I was particularly puzzled by the version constraints and what they were based on. This is why I didn't replicate the same config originally.

2024-10-03 14:46 UTC, ryanskeith commented on recipe/meta.yaml
> +    - snowflake-snowpark-python
Going back in time will always be somewhat messy.  Thank you for getting up to speed as fast as you are.  We really appreciate it.

2024-10-03 15:01 UTC, ryanskeith approved these changes
LGTM.

2024-10-03 15:13 UTC, skupr-anaconda approved these changes

2024-10-03 15:39 UTC, merged